version: "3.3"

services:
  nginx:
    build:                                  
      context: .                             
      dockerfile: docker/Nginx.Dockerfile    
    ports:
      - 8098:80
    links:                                   
      - fpm                                
  fpm:                                       
    build:                                   
      context: .                             
      dockerfile: docker/Fpm.Dockerfile       
    volumes:                                                
      - ./:/home/alexander/Документы/GitHub/laravel_shop2   
    links:                                                 
      - mysql                                             
  mysql:                                                    
    image:5.7                                             
    ports:                                                  
      - 33061:3306                                         
    environment:                                            
      - MYSQL_ROOT_PASSWORD=root                           
      - MYSQL_DATABASE=laravel 